#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpath-rw
Version  : 1.4.0
Release  : 16
URL      : http://pypi.debian.net/jsonpath-rw/jsonpath-rw-1.4.0.tar.gz
Source0  : http://pypi.debian.net/jsonpath-rw/jsonpath-rw-1.4.0.tar.gz
Summary  : A robust and significantly extended implementation of JSONPath for Python, with a clear AST for metaprogramming.
Group    : Development/Tools
License  : Apache-2.0
Requires: jsonpath-rw-bin
Requires: jsonpath-rw-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Python JSONPath RW
==================
https://github.com/kennknowles/python-jsonpath-rw

%package bin
Summary: bin components for the jsonpath-rw package.
Group: Binaries

%description bin
bin components for the jsonpath-rw package.


%package python
Summary: python components for the jsonpath-rw package.
Group: Default

%description python
python components for the jsonpath-rw package.


%prep
%setup -q -n jsonpath-rw-1.4.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jsonpath.py

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
